apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-test
  name: nginx-deployment
  labels:     # 自定义资源的标签
    app: web2
    appName: nginx-web2
    version: stable
spec:
  selector:
    matchLabels:
      app: web
      appName: nginx-web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
        appName: nginx-web
    spec:
      containers:
        - name: nginx
          image: 192.144.178.98:443/my/nginx:latest
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - containerPort: 80