apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-test
  name: nginx-deployment
  labels:     # 自定义资源的标签
    app: web2
    appName: nginx-web2
    version: {{APP_VERSION}}
spec:
  revisionHistoryLimit: 1 #可指定为该 Deployment 保留多少个旧的 ReplicaSet。
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: web
      appName: nginx-web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
        appName: nginx-web
    spec:
      containers:
        - name: nginx
          image: {{IMG_NAME}}
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - containerPort: 80