podTemplate {
    node(POD_LABEL) {
        stage('Run shell') {
            sh 'echo hello world'
        }
    }
}

{
//     agent any
    node("jenkins-slave"){
        stage('build image') {
            steps {
                echo "----------------------从git仓库拉取代码阶段------------------"
                git branch: 'main', credentialsId: '5c26cc66-ec4d-40aa-a261-58f29df53b76', url: 'git@github.com:metrosir/test.git'
            }
        }
        stage('Docker Builder') {
            steps {
                echo "----------------------生产docker镜像------------------"
                sh '''
                docker login -u t1 -p 'Oa123!@#' 192.144.178.98:443
                docker build -t 192.144.178.98:443/my/nginx:latest -f project/Dockerfile .
                docker push 192.144.178.98:443/my/nginx:latest
                '''
            }
        }
        stage('Deploy to K8S'){
            steps {
                echo "----------------------kubernetesDeploy------------------"
                kubernetesDeploy configs: 'deploy/deploy.yaml'
                kubeconfig(credentialsId: '819c6052-037c-4f44-ae98-f3c666eafab2', serverUrl: 'https://10.0.16.9:6443') {
                    // some block
                }
            }
            steps {
                echo "Testing..."
            }
        }
    }
//     stages {
}



//     stage {
//             stage('build') {
//                 agent {
//                     docker {
//                         image 'php'
//                     }
//                 }
//                 steps {
//                     sh 'php --version'
//                 }
//             }
//     }

// 依次安装：docker-commons,docker-java-api,docker-build-step,docker-workflow(dockerpipline),rancher
// [pipeline的编写] 1.https://blog.csdn.net/superman26/article/details/120697735
//                 2.https://www.cnblogs.com/shawhe/p/11313633.html
// [docker 容器部署jenkins时在在容器中又要用到docker相关的操作该怎么处理]https://www.cnblogs.com/minimeta/p/16490444.html

// [kubernetes-plugin] https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/service-account.yml
//                     https://github.com/jenkinsci/kubernetes-plugin/tree/master/examples
//                     https://hub.docker.com/r/jenkins/inbound-agent